spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
#    url: jdbc:h2:mem:test;DATABASE_TO_UPPER=false
    url: jdbc:mysql://192.168.1.24:3306/company?useSSL=false&serverTimezone=Europe/Warsaw
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: n2god
    password: 46812123aXXdatabase!
  jpa:
#    defer-datasource-initialization: true #plik z danymi testowym z /resources/data.sql i wykona się po wygenerowaniu schematu bazy danych przez Hibernate
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: update #tylko update bazy danych
#  sql:
#    init:
#      mode: always #wykonanie skryptu z /resources/schema.sql i /resources/data.sql czyli to samo co create z ddl-auto wyżej no i dodatkowo dane testowe
